$(document).ready(function(event){
	$('.autor-button').click(function(event){
		$('.autor-button').css('background','#17335E');
		$('.custom-button').css('background','#334D75');
		$('.customer-menu').css('display','none');
		$('.autor-menu').css('display','block');
	});
	$('.custom-button').click(function(event){
		$('.custom-button').css('background','#17335E');
		$('.autor-button').css('background','#334D75');
		$('.autor-menu').css('display','none');
		$('.customer-menu').css('display','block');
	});
	$('.account').click(function(event){
		$('.personal-dropdown').toggleClass('personal-dropdown-active');
		$('.account').toggleClass('account-active');
		$('.autor-menu').css('display','none');
		$('.customer-menu').css('display','block');
		$('.custom-button').css('background','#17335E');
		$('.autor-button').css('background','#334D75');
	});
	$('.flag-russia').click(function(event){
		$('.country').toggleClass('country-active');
		$('.personal-name span').toggleClass('russian-active');
	})
	$('.info-drop-down').click(function(event){
		$('.info-down').toggleClass('info-down-active');
		$('.down-arrow-one').toggleClass('down-arrow-active');
		$('.info-drop-down').toggleClass('info-drop-down-active');
	});
	$('.down-list-one').click(function(event){
		$('.info-group p').text('Пункт 1');
	});
	$('.down-list-two').click(function(event){
		$('.info-group p').text('Пункт 2');
	});
	$('.down-list-three').click(function(event){
		$('.info-group p').text('Пункт 3');
	});
	$('.data-drop-down').click(function(event){
		$('.data-down').toggleClass('data-down-active');
		$('.down-arrow-two').toggleClass('down-arrow-active');
		$('.projects-data').toggleClass('projects-data-active');
	});
	$('.data-list-one').click(function(event){
		$('.data-group p').text('Пункт 1');
	});
	$('.data-list-two').click(function(event){
		$('.data-group p').text('Пункт 2');
	});
	$('.data-list-three').click(function(event){
		$('.data-group p').text('Пункт 3');
	});
	$('.one').hover(function(event){
		$('.img-one').toggleClass('img-pass');
		$('.img-first').toggleClass('img-active');
	});
	$('.two').hover(function(event){
		$('.img-two').toggleClass('img-pass');
		$('.img-second').toggleClass('img-active');
	});
	$('.three').hover(function(event){
		$('.img-three').toggleClass('img-pass');
		$('.img-third').toggleClass('img-active');
	});
	$('.back-1').hover(function(event){
		$('.color-normal-1').toggleClass('color-normal-active');
		$('.color-fff-1').toggleClass('color-fff-active');
	});
	$('.back-2').hover(function(event){
		$('.color-normal-2').toggleClass('color-normal-active');
		$('.color-fff-2').toggleClass('color-fff-active');
	});
	$('.back-3').hover(function(event){
		$('.color-normal-3').toggleClass('color-normal-active');
		$('.color-fff-3').toggleClass('color-fff-active');
	});
	$('.back-4').hover(function(event){
		$('.color-normal-4').toggleClass('color-normal-active');
		$('.color-fff-4').toggleClass('color-fff-active');
	});
	$('.back-5').hover(function(event){
		$('.color-normal-5').toggleClass('color-normal-active');
		$('.color-fff-5').toggleClass('color-fff-active');
	});
	$('.back-6').hover(function(event){
		$('.color-normal-6').toggleClass('color-normal-active');
		$('.color-fff-6').toggleClass('color-fff-active');
	});
	$('.back-7').hover(function(event){
		$('.color-normal-7').toggleClass('color-normal-active');
		$('.color-fff-7').toggleClass('color-fff-active');
	});
	$('.back-8').hover(function(event){
		$('.color-normal-8').toggleClass('color-normal-active');
		$('.color-fff-8').toggleClass('color-fff-active');
	});
	$('.back-9').hover(function(event){
		$('.color-normal-9').toggleClass('color-normal-active');
		$('.color-fff-9').toggleClass('color-fff-active');
	});
	$('.back-10').hover(function(event){
		$('.color-normal-10').toggleClass('color-normal-active');
		$('.color-fff-10').toggleClass('color-fff-active');
	});
	$('.back-11').hover(function(event){
		$('.color-normal-11').toggleClass('color-normal-active');
		$('.color-fff-11').toggleClass('color-fff-active');
	});
	$('.back-12').hover(function(event){
		$('.color-normal-12').toggleClass('color-normal-active');
		$('.color-fff-12').toggleClass('color-fff-active');
	});
	$('.back-13').hover(function(event){
		$('.color-normal-13').toggleClass('color-normal-active');
		$('.color-fff-13').toggleClass('color-fff-active');
	});
	$('.back-14').hover(function(event){
		$('.color-normal-14').toggleClass('color-normal-active');
		$('.color-fff-14').toggleClass('color-fff-active');
	});
	$('.back-15').hover(function(event){
		$('.color-normal-15').toggleClass('color-normal-active');
		$('.color-fff-15').toggleClass('color-fff-active');
	});
	$('.back-16').hover(function(event){
		$('.color-normal-16').toggleClass('color-normal-active');
		$('.color-fff-16').toggleClass('color-fff-active');
	});
	$('.back-17').hover(function(event){
		$('.color-normal-17').toggleClass('color-normal-active');
		$('.color-fff-17').toggleClass('color-fff-active');
	});
	$('.back-18').hover(function(event){
		$('.color-normal-18').toggleClass('color-normal-active');
		$('.color-fff-18').toggleClass('color-fff-active');
	});
	$('.back-19').hover(function(event){
		$('.color-normal-19').toggleClass('color-normal-active');
		$('.color-fff-19').toggleClass('color-fff-active');
	});
	$('.back-20').hover(function(event){
		$('.color-normal-20').toggleClass('color-normal-active');
		$('.color-fff-20').toggleClass('color-fff-active');
	});
	$('.back-21').hover(function(event){
		$('.color-normal-21').toggleClass('color-normal-active');
		$('.color-fff-21').toggleClass('color-fff-active');
	});
	$('.back-22').hover(function(event){
		$('.color-normal-22').toggleClass('color-normal-active');
		$('.color-fff-22').toggleClass('color-fff-active');
	});
	$('.back-23').hover(function(event){
		$('.color-normal-23').toggleClass('color-normal-active');
		$('.color-fff-23').toggleClass('color-fff-active');
	});
	$('.back-24').hover(function(event){
		$('.color-normal-24').toggleClass('color-normal-active');
		$('.color-fff-24').toggleClass('color-fff-active');
	});
	$('.back-25').hover(function(event){
		$('.color-normal-25').toggleClass('color-normal-active');
		$('.color-fff-25').toggleClass('color-fff-active');
	});
	$('.back-26').hover(function(event){
		$('.color-normal-26').toggleClass('color-normal-active');
		$('.color-fff-26').toggleClass('color-fff-active');
	});
	$('.back-27').hover(function(event){
		$('.color-normal-27').toggleClass('color-normal-active');
		$('.color-fff-27').toggleClass('color-fff-active');
	});
	$('.back-28').hover(function(event){
		$('.color-normal-28').toggleClass('color-normal-active');
		$('.color-fff-28').toggleClass('color-fff-active');
	});
});

document.body.onload = function() {

    setTimeout(function() {
    var preloader = document.getElementById('preloader');
    if(!preloader.classList.contains('done') ) {
    preloader.classList.add('done');
    }
    }, 1500);
 }